working_dir: EveNet-Full
spanet_dir: SPANet
train_yaml: train.yaml
predict_yaml: predict.yaml
process_json: process.json
stat_yaml: Statistics_Test.yaml
#input_dir:
#  - /global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/data/HAA.20250621
#  - /global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/data/HAA.20250620
#  - /global/cfs/cdirs/m2616/avencast/Event_Level_Analysis/data/HAA.20250619
account: m5019
email: tihsu
time: 04:00:00
job_flavor: regular
spanet:
  project: ExoticHiggsDecay

pretrain_choice:
  pretrain:
    path: pretrain-weights/checkpoints.20M.a4.last.ckpt
    option: options_pretrain.yaml
  pretrain-SSL:
    path: pretrain-weights/SSL.20M.last.ckpt
    option: options_pretrain.yaml
  scratch:
    path: null
    option: options.yaml

image: 'docker:avencast1994/evenet:1.5'
assign_seg_choice:
  - [true, true]
  - [true, false]
  - [false, true]
  - [false, false]

dataset_size_choice:
  - 0.01
  - 0.03
  - 0.1
  - 0.3
  - 1.0

mass_choice:
  - 30
